# Basics

In [3]:
import numpy as np
np.__version__

'1.24.1'

## 1D Array

In [4]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [5]:
type(x)

numpy.ndarray

In [6]:
x.ndim

1

In [7]:
x.shape

(6,)

In [8]:
x.size

6

In [9]:
x.dtype

dtype('int32')

## 2d Array


In [13]:
matrix = np.array([[1, 2, 3], [1.2, 5, 34]])
matrix

array([[ 1. ,  2. ,  3. ],
       [ 1.2,  5. , 34. ]])

In [12]:
print(matrix.dtype)
print(matrix.ndim)
print(matrix.shape)

float64
2
(2, 3)


## 3d Array


In [19]:
x = np.array(
    [
        [
            [1, 4, 5],
            [6, 4, 3]
        ],
        [
            [5, 2, 1],
            [6, 4, 3]
        ]
    ]
)
print(x)

[[[1 4 5]
  [6 4 3]]

 [[5 2 1]
  [6 4 3]]]


In [17]:
x.ndim

3

In [18]:
x.shape

(2, 2, 3)